/* Technology Store Admin V8 — full commerce controls + source analytics */
(() => {
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>`${new Intl.NumberFormat('ar-EG',{maximumFractionDigits:2}).format(Number(n)||0)} ج.م`;
  async function api(url, init={}){
    const headers=new Headers(init.headers||{}); const token=sessionStorage.getItem('tech_admin_token'); if(token)headers.set('Authorization',`Bearer ${token}`);
    if(init.body && !(init.body instanceof FormData) && typeof init.body!=='string'){headers.set('Content-Type','application/json');init.body=JSON.stringify(init.body);}
    const r=await fetch(url,{...init,headers}); let data={}; try{data=await r.json();}catch(_){} if(!r.ok)throw new Error(data.message||`HTTP ${r.status}`); return data;
  }
  function toast(msg){ if(window.showToast)window.showToast(msg); else alert(msg); }
  function canManage(){try{const u=JSON.parse(sessionStorage.getItem('tech_current_user')||'{}');return (u.permissions||[]).includes('all')||(u.permissions||[]).includes('manage_settings');}catch(_){return false;}}
  function canManageGrowth(){try{const u=JSON.parse(sessionStorage.getItem('tech_current_user')||'{}');return (u.permissions||[]).includes('all')||(u.permissions||[]).includes('manage_settings')||(u.permissions||[]).includes('manage_marketing');}catch(_){return false;}}

  // ---------------- Product variants builder ----------------
  function variantSection(prefix){
    const edit=prefix==='editP'; const id=edit?'editPVariantsJson':'pVariantsJson'; const rows=edit?'editVariantRows':'variantRows';
    return `<section class="${edit?'product-edit-section':'product-form-section'} v8-admin-variants">
      <div class="${edit?'product-edit-section-title':'product-form-section__title'}"><span class="material-symbols-outlined">tune</span><div><strong>خيارات المنتج / Variants</strong><small>مثل اللون أو السعة، ولكل خيار سعر ومخزون وSKU مستقل.</small></div></div>
      <input type="hidden" id="${id}" value="[]"><div id="${rows}" class="v8-variant-admin-list"></div>
      <button type="button" class="admin-action-btn" data-add-variant="${prefix}"><span class="material-symbols-outlined">add</span> إضافة خيار</button>
    </section>`;
  }
  function injectVariantBuilders(){
    const add=document.getElementById('addProductForm');
    if(add&&!document.getElementById('pVariantsJson')){const seo=add.querySelector('.product-form-section:nth-last-of-type(2)');(seo||add.querySelector('.admin-sidepanel__footer')).insertAdjacentHTML('beforebegin',variantSection('p'));}
    const edit=document.getElementById('editProductForm');
    if(edit&&!document.getElementById('editPVariantsJson')){const footer=edit.querySelector('.product-edit-footer');footer?.insertAdjacentHTML('beforebegin',variantSection('editP'));}
    document.querySelectorAll('[data-add-variant]').forEach(b=>b.onclick=()=>addVariantRow(b.dataset.addVariant));
    document.getElementById('addProductForm')?.addEventListener('reset',()=>setTimeout(()=>{document.getElementById('variantRows').innerHTML='';syncVariants('p');},0));
  }
  function addVariantRow(prefix, data={}){
    const edit=prefix==='editP'; const host=document.getElementById(edit?'editVariantRows':'variantRows'); if(!host)return;
    const row=document.createElement('div');row.className='v8-variant-admin-row';row.innerHTML=`
      <input data-k="label" placeholder="نوع الخيار (مثال: اللون)" value="${esc(data.label||'')}">
      <input data-k="value" placeholder="القيمة (أسود / 256GB)" value="${esc(data.value||'')}">
      <input data-k="price" type="number" step="0.01" min="0" placeholder="السعر" value="${data.price??''}">
      <input data-k="oldPrice" type="number" step="0.01" min="0" placeholder="قبل الخصم" value="${data.oldPrice??''}">
      <input data-k="stockQuantity" type="number" min="0" placeholder="المخزون" value="${data.stockQuantity??0}">
      <input data-k="sku" placeholder="SKU" value="${esc(data.sku||'')}">
      <input data-k="image" placeholder="رابط صورة الخيار (اختياري)" value="${esc(data.image||'')}">
      <button type="button" title="حذف"><span class="material-symbols-outlined">delete</span></button>`;
    host.appendChild(row); row.querySelectorAll('input').forEach(i=>i.addEventListener('input',()=>syncVariants(prefix))); row.querySelector('button').onclick=()=>{row.remove();syncVariants(prefix);}; syncVariants(prefix);
  }
  function syncVariants(prefix){
    const edit=prefix==='editP'; const host=document.getElementById(edit?'editVariantRows':'variantRows'),hidden=document.getElementById(edit?'editPVariantsJson':'pVariantsJson');if(!host||!hidden)return;
    const arr=[...host.children].map(row=>{const o={};row.querySelectorAll('[data-k]').forEach(i=>{let v=i.value.trim();if(['price','oldPrice','stockQuantity'].includes(i.dataset.k))v=v===''?undefined:Number(v);o[i.dataset.k]=v;});return o;}).filter(v=>v.value);hidden.value=JSON.stringify(arr);
  }
  function renderEditVariants(product){const host=document.getElementById('editVariantRows');if(!host)return;host.innerHTML='';(product?.variants||[]).forEach(v=>addVariantRow('editP',v));syncVariants('editP');}

  // Wrap edit modal after original admin script loaded.
  function wrapEditModal(){if(!window.openEditModal||window.openEditModal.__v8)return;const old=window.openEditModal;const wrapped=function(id){old(id);const p=(window.adminProducts||[]).find(x=>String(x._id)===String(id));setTimeout(()=>renderEditVariants(p),0);};wrapped.__v8=true;window.openEditModal=wrapped;}

  // ---------------- Shipping & payment controls ----------------
  function injectCommerceSettings(){const panel=document.getElementById('panel-settings');if(!panel||document.getElementById('v8CommerceSettings'))return;const card=document.createElement('div');card.id='v8CommerceSettings';card.className='glass-panel p-5 rounded-xl border border-outline-variant/50 lg:col-span-3';card.innerHTML=`
    <div class="v8-admin-title"><div><span class="material-symbols-outlined">local_shipping</span><div><h3>الشحن والدفع والخصوصية</h3><p>تحكم كامل في مناطق الشحن، الشحن المجاني وطرق الدفع.</p></div></div><button id="v8SaveCommerce" class="admin-action-btn admin-action-btn--primary"><span class="material-symbols-outlined">save</span> حفظ</button></div>
    <div class="v8-commerce-grid">
      <label><span>تفعيل الشحن</span><input type="checkbox" id="v8ShippingEnabled"></label>
      <label><span>السماح بالاستلام من المعرض</span><input type="checkbox" id="v8PickupEnabled"></label>
      <label><span>شحن مجاني من إجمالي</span><input type="number" id="v8FreeShipping" min="0" step="1" placeholder="0 = غير مفعل"></label>
      <label><span>الدفع عند الاستلام</span><input type="checkbox" id="v8PayCOD"></label>
      <label><span>InstaPay</span><input type="checkbox" id="v8PayInstapay"></label>
      <label><span>الدفع في المعرض</span><input type="checkbox" id="v8PayStore"></label>
      <label class="wide"><span>InstaPay Handle / رقم التحويل</span><input id="v8InstapayHandle" dir="ltr"></label>
      <label class="wide"><span>تعليمات الشحن</span><textarea id="v8ShippingInstructions" rows="2"></textarea></label>
    </div>
    <div class="v8-zones-head"><div><strong>مناطق الشحن</strong><small>اسم المنطقة + التكلفة + المدة المتوقعة.</small></div><button id="v8AddZone" class="admin-action-btn"><span class="material-symbols-outlined">add</span> منطقة</button></div>
    <div id="v8Zones" class="v8-zones"></div>`;
    panel.querySelector('.grid')?.appendChild(card);document.getElementById('v8AddZone').onclick=()=>addZone();document.getElementById('v8SaveCommerce').onclick=saveCommerceSettings;loadCommerceSettings();}
  function addZone(z={}){const host=document.getElementById('v8Zones');if(!host)return;const row=document.createElement('div');row.className='v8-zone-row';row.innerHTML=`<input data-k="name" placeholder="القاهرة / الجيزة..." value="${esc(z.name||'')}"><input data-k="fee" type="number" min="0" step="1" placeholder="التكلفة" value="${z.fee??0}"><input data-k="eta" placeholder="مثال: 1-2 يوم" value="${esc(z.eta||'')}"><label><input data-k="enabled" type="checkbox" ${z.enabled===false?'':'checked'}> مفعل</label><button type="button"><span class="material-symbols-outlined">delete</span></button>`;host.appendChild(row);row.querySelector('button').onclick=()=>row.remove();}
  async function loadCommerceSettings(){if(!canManage())return;try{const s=await api('/api/settings');const set=(id,v)=>{const e=document.getElementById(id);if(!e)return;if(e.type==='checkbox')e.checked=Boolean(v);else e.value=v??'';};set('v8ShippingEnabled',s.isShippingEnabled);set('v8PickupEnabled',s.pickupEnabled!==false);set('v8FreeShipping',s.freeShippingThreshold||0);set('v8PayCOD',s.paymentCashOnDelivery!==false);set('v8PayInstapay',s.paymentInstapay);set('v8PayStore',s.paymentStorePickup!==false);set('v8InstapayHandle',s.instapayHandle);set('v8ShippingInstructions',s.shippingInstructions);const host=document.getElementById('v8Zones');if(host){host.innerHTML='';(s.shippingZones||[]).forEach(addZone);}}catch(e){console.error(e);}}
  async function saveCommerceSettings(){try{const zones=[...document.querySelectorAll('#v8Zones .v8-zone-row')].map(r=>({name:r.querySelector('[data-k="name"]').value.trim(),governorate:r.querySelector('[data-k="name"]').value.trim(),fee:Number(r.querySelector('[data-k="fee"]').value||0),eta:r.querySelector('[data-k="eta"]').value.trim(),enabled:r.querySelector('[data-k="enabled"]').checked})).filter(z=>z.name);await api('/api/settings',{method:'POST',body:{isShippingEnabled:document.getElementById('v8ShippingEnabled').checked,pickupEnabled:document.getElementById('v8PickupEnabled').checked,freeShippingThreshold:Number(document.getElementById('v8FreeShipping').value||0),paymentCashOnDelivery:document.getElementById('v8PayCOD').checked,paymentInstapay:document.getElementById('v8PayInstapay').checked,paymentStorePickup:document.getElementById('v8PayStore').checked,instapayHandle:document.getElementById('v8InstapayHandle').value.trim(),shippingInstructions:document.getElementById('v8ShippingInstructions').value.trim(),shippingZones:zones}});toast('✅ تم حفظ إعدادات الشحن والدفع');}catch(e){alert(e.message);}}

  // ---------------- Growth / customer trust tab ----------------
  function injectGrowthTab(){if(document.getElementById('tab-growth'))return;const anchor=document.getElementById('tab-analytics');if(!anchor)return;const b=document.createElement('button');b.id='tab-growth';b.className='admin-tab w-full flex items-center gap-3 px-4 py-3 rounded-lg text-on-surface-variant font-bold text-sm transition-all hover:bg-surface-variant/50';b.innerHTML='<span class="material-symbols-outlined">rocket_launch</span><span>المبيعات والعملاء</span>';b.onclick=()=>window.switchTab('growth');anchor.before(b);const parent=document.getElementById('panel-settings')?.parentElement;if(!parent)return;const panel=document.createElement('div');panel.id='panel-growth';panel.className='tab-panel hidden';panel.innerHTML=`
    <div class="v8-growth-head"><div><h2>المبيعات والعملاء</h2><p>الكوبونات، تقييمات العملاء، طلبات التنبيه عند عودة المخزون.</p></div><button class="admin-action-btn" onclick="window.v8LoadGrowth()"><span class="material-symbols-outlined">refresh</span> تحديث</button></div>
    <div class="v8-growth-grid">
      <section class="glass-panel v8-growth-card v8-campaign-card"><h3><span class="material-symbols-outlined">link</span> منشئ روابط الحملات المتتبعة</h3><p class="v8-admin-help">استخدم الرابط الناتج في فيسبوك أو واتساب أو أي منصة لكي يظهر المصدر والحملة بدقة حتى لو المنصة لا ترسل Referrer.</p><div class="v8-campaign-form"><input id="v8CampaignPath" placeholder="رابط أو مسار مثل /products" value="/products"><select id="v8CampaignSource"><option value="facebook">Facebook</option><option value="whatsapp">WhatsApp</option><option value="instagram">Instagram</option><option value="tiktok">TikTok</option><option value="telegram">Telegram</option><option value="youtube">YouTube</option><option value="qr">QR / مطبوعات</option><option value="custom">مصدر مخصص</option></select><input id="v8CampaignCustom" class="hidden" placeholder="اسم المصدر المخصص"><input id="v8CampaignName" placeholder="اسم الحملة (مثال: october_offer)"><button id="v8MakeCampaign" class="admin-action-btn admin-action-btn--primary">إنشاء الرابط</button></div><div id="v8CampaignResult" class="v8-campaign-result hidden"><input id="v8CampaignUrl" readonly dir="ltr"><button id="v8CopyCampaign" class="admin-action-btn">نسخ</button></div></section>
      <section class="glass-panel v8-growth-card"><h3><span class="material-symbols-outlined">sell</span> كوبونات الخصم</h3><div class="v8-coupon-form"><input id="v8CouponCode" placeholder="CODE"><select id="v8CouponType"><option value="percent">نسبة %</option><option value="fixed">مبلغ ثابت</option></select><input id="v8CouponValue" type="number" min="0" placeholder="القيمة"><input id="v8CouponMin" type="number" min="0" placeholder="حد أدنى"><input id="v8CouponMax" type="number" min="0" placeholder="حد أقصى للخصم"><input id="v8CouponLimit" type="number" min="0" placeholder="مرات الاستخدام (0=∞)"><input id="v8CouponStart" type="datetime-local"><input id="v8CouponEnd" type="datetime-local"><button id="v8AddCoupon" class="admin-action-btn admin-action-btn--primary">إضافة كوبون</button></div><div id="v8CouponsList"></div></section>
      <section class="glass-panel v8-growth-card"><h3><span class="material-symbols-outlined">star</span> التقييمات المنتظرة</h3><div id="v8ReviewsAdmin"></div></section>
      <section class="glass-panel v8-growth-card"><h3><span class="material-symbols-outlined">notifications_active</span> تنبيهات توفر المخزون</h3><div id="v8StockAlerts"></div></section>
    </div>`;parent.appendChild(panel);document.getElementById('v8AddCoupon').onclick=addCoupon;
    const source=document.getElementById('v8CampaignSource');if(source)source.onchange=()=>document.getElementById('v8CampaignCustom')?.classList.toggle('hidden',source.value!=='custom');
    document.getElementById('v8MakeCampaign').onclick=makeCampaignLink;document.getElementById('v8CopyCampaign').onclick=copyCampaignLink;wrapSwitchTab();}
  function makeCampaignLink(){
    const raw=document.getElementById('v8CampaignPath')?.value.trim()||'/products';
    const sel=document.getElementById('v8CampaignSource')?.value||'facebook';
    const custom=document.getElementById('v8CampaignCustom')?.value.trim()||'';
    const campaign=(document.getElementById('v8CampaignName')?.value.trim()||'store_campaign').replace(/\s+/g,'_');
    const source=sel==='custom'?(custom||'custom'):sel;
    let u;try{u=new URL(raw,location.origin);}catch(_){u=new URL('/products',location.origin);}
    u.searchParams.set('utm_source',source);u.searchParams.set('utm_medium',sel==='qr'?'offline':'campaign');u.searchParams.set('utm_campaign',campaign);u.searchParams.set('share_source',source);
    const out=document.getElementById('v8CampaignUrl'),box=document.getElementById('v8CampaignResult');if(out)out.value=u.toString();box?.classList.remove('hidden');
  }
  async function copyCampaignLink(){const value=document.getElementById('v8CampaignUrl')?.value||'';if(!value)return;try{await navigator.clipboard.writeText(value);toast('✅ تم نسخ رابط الحملة');}catch(_){document.getElementById('v8CampaignUrl')?.select();}}

  async function addCoupon(){try{await api('/api/admin/coupons',{method:'POST',body:{code:document.getElementById('v8CouponCode').value,type:document.getElementById('v8CouponType').value,value:Number(document.getElementById('v8CouponValue').value||0),minSubtotal:Number(document.getElementById('v8CouponMin').value||0),maxDiscount:Number(document.getElementById('v8CouponMax').value||0),usageLimit:Number(document.getElementById('v8CouponLimit').value||0),startsAt:document.getElementById('v8CouponStart').value||undefined,endsAt:document.getElementById('v8CouponEnd').value||undefined,enabled:true}});toast('✅ تمت إضافة الكوبون');loadGrowth();}catch(e){alert(e.message);}}
  async function loadGrowth(){if(!canManageGrowth())return;try{const [coupons,reviews,alerts]=await Promise.all([api('/api/admin/coupons'),api('/api/admin/reviews'),api('/api/admin/stock-notify')]);renderCoupons(coupons);renderReviews(reviews);renderAlerts(alerts);}catch(e){console.error(e);}}
  window.v8LoadGrowth=loadGrowth;
  function renderCoupons(list){const h=document.getElementById('v8CouponsList');if(!h)return;h.innerHTML=list.length?list.map(c=>`<div class="v8-admin-item"><div><strong>${esc(c.code)}</strong><small>${c.type==='percent'?`${c.value}%`:money(c.value)} • حد أدنى ${money(c.minSubtotal||0)} • استخدام ${c.usedCount||0}${c.usageLimit?` / ${c.usageLimit}`:''}${c.endsAt?` • ينتهي ${new Date(c.endsAt).toLocaleDateString('ar-EG')}`:''}</small></div><label><input type="checkbox" ${c.enabled?'checked':''} onchange="window.v8ToggleCoupon('${c._id}',this.checked)"> مفعل</label><div class="v8-admin-actions"><button onclick="window.v8EditCoupon('${c._id}')">تعديل</button><button class="danger" onclick="window.v8DeleteCoupon('${c._id}')"><span class="material-symbols-outlined">delete</span></button></div></div>`).join(''):'<p class="v8-admin-empty">لا توجد كوبونات.</p>';window.__v8Coupons=list;}
  window.v8EditCoupon=async id=>{const c=(window.__v8Coupons||[]).find(x=>x._id===id);if(!c)return;const value=prompt('قيمة الخصم:',String(c.value??0));if(value===null)return;const min=prompt('الحد الأدنى للطلب:',String(c.minSubtotal??0));if(min===null)return;const max=prompt('الحد الأقصى للخصم (0 بدون حد):',String(c.maxDiscount??0));if(max===null)return;const limit=prompt('عدد مرات الاستخدام (0 بدون حد):',String(c.usageLimit??0));if(limit===null)return;try{await api(`/api/admin/coupons/${id}`,{method:'PUT',body:{value:Number(value)||0,minSubtotal:Number(min)||0,maxDiscount:Number(max)||0,usageLimit:Number(limit)||0}});toast('✅ تم تعديل الكوبون');loadGrowth();}catch(e){alert(e.message);}};
  window.v8ToggleCoupon=async(id,enabled)=>{try{await api(`/api/admin/coupons/${id}`,{method:'PUT',body:{enabled}});toast('تم التحديث');}catch(e){alert(e.message);}};
  window.v8DeleteCoupon=async id=>{if(!confirm('حذف الكوبون؟'))return;try{await api(`/api/admin/coupons/${id}`,{method:'DELETE'});loadGrowth();}catch(e){alert(e.message);}};
  function renderReviews(list){const h=document.getElementById('v8ReviewsAdmin');if(!h)return;h.innerHTML=list.length?list.map(r=>`<div class="v8-review-admin ${r.approved?'approved':''}"><div><strong>${esc(r.productId?.title||'منتج')}</strong><span>${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</span></div><p><b>${esc(r.name)}</b> — ${esc(r.comment||'بدون تعليق')}</p><small>${new Date(r.createdAt).toLocaleString('ar-EG')}</small><div class="v8-admin-actions"><button onclick="window.v8ApproveReview('${r._id}',${!r.approved})">${r.approved?'إخفاء':'اعتماد ونشر'}</button><button class="danger" onclick="window.v8DeleteReview('${r._id}')">حذف</button></div></div>`).join(''):'<p class="v8-admin-empty">لا توجد تقييمات.</p>';}
  window.v8ApproveReview=async(id,approved)=>{await api(`/api/admin/reviews/${id}`,{method:'PUT',body:{approved}});loadGrowth();};window.v8DeleteReview=async id=>{if(confirm('حذف التقييم؟')){await api(`/api/admin/reviews/${id}`,{method:'DELETE'});loadGrowth();}};
  function renderAlerts(list){const h=document.getElementById('v8StockAlerts');if(!h)return;h.innerHTML=list.length?list.map(a=>`<div class="v8-admin-item"><div><strong>${esc(a.productTitle||'منتج')}</strong><small>${esc(a.name||'عميل')} • <span dir="ltr">${esc(a.phone)}</span> • ${a.status==='waiting'?'بانتظار التنبيه':a.status==='notified'?'تم التنبيه':'ملغي'}</small></div><div class="v8-admin-actions">${a.status==='waiting'?`<button onclick="window.v8SendStockWhatsapp('${a._id}','${esc(a.phone)}','${esc(a.productTitle||'المنتج')}')">واتساب</button><button onclick="window.v8AlertStatus('${a._id}','notified')">تم التنبيه</button>`:''}<button class="danger" onclick="window.v8DeleteAlert('${a._id}')">حذف</button></div></div>`).join(''):'<p class="v8-admin-empty">لا توجد طلبات تنبيه.</p>';}
  window.v8SendStockWhatsapp=async(id,phone,title)=>{const n=String(phone||'').replace(/\D/g,'');const msg=encodeURIComponent(`مرحباً، المنتج ${title} أصبح متاحاً الآن في TECHNOLOGY STORE. يمكنك طلبه من الموقع: ${location.origin}/products`);window.open(`https://wa.me/${n}?text=${msg}`,'_blank','noopener');try{await api(`/api/admin/stock-notify/${id}`,{method:'PUT',body:{status:'notified'}});setTimeout(loadGrowth,300);}catch(_){}};
  window.v8AlertStatus=async(id,status)=>{await api(`/api/admin/stock-notify/${id}`,{method:'PUT',body:{status}});loadGrowth();};window.v8DeleteAlert=async id=>{if(confirm('حذف الطلب؟')){await api(`/api/admin/stock-notify/${id}`,{method:'DELETE'});loadGrowth();}};

  // ---------------- Rich acquisition analytics ----------------
  function injectAnalyticsSourceUI(){const table=document.getElementById('analytics-visitors-table')?.closest('table');if(!table||document.getElementById('v8SourceSummary'))return;table.querySelector('thead tr').innerHTML='<th>الزائر / العميل</th><th>آخر زيارة</th><th>المصدر الحالي</th><th>الحملة</th><th>صفحة الدخول</th><th>الموقع / IP</th><th>الجهاز</th><th>أول مصدر</th><th>الجلسات</th><th>Visitor ID</th><th>التفاصيل</th>';table.classList.add('v8-wide-table');const card=table.closest('.glass-panel');card?.querySelector('h3')?.insertAdjacentHTML('afterend','<div class="v8-analytics-controls"><label>من <input type="date" id="v8AnalyticsFrom"></label><label>إلى <input type="date" id="v8AnalyticsTo"></label><button id="v8AnalyticsApply" class="admin-action-btn">تطبيق</button><button id="v8AnalyticsReset" class="admin-action-btn">الكل</button><button id="v8ExportVisitors" class="admin-action-btn">CSV الزوار</button><button id="v8ExportSessions" class="admin-action-btn">CSV الجلسات</button></div><div id="v8SourceSummary" class="v8-source-summary"></div>');setTimeout(()=>{const a=document.getElementById('v8AnalyticsApply'),r=document.getElementById('v8AnalyticsReset'),ev=document.getElementById('v8ExportVisitors'),es=document.getElementById('v8ExportSessions');if(a)a.onclick=()=>window.loadUniqueVisitors?.();if(r)r.onclick=()=>{document.getElementById('v8AnalyticsFrom').value='';document.getElementById('v8AnalyticsTo').value='';window.__v8SourceFilter='';window.loadUniqueVisitors?.();};if(ev)ev.onclick=()=>exportAnalyticsCsv('visitors');if(es)es.onclick=()=>exportAnalyticsCsv('sessions');},0);card?.insertAdjacentHTML('afterend','<div class="glass-panel p-6 rounded-xl border border-outline-variant/30 mb-8"><h3 class="font-headline-md text-lg text-on-surface mb-4 flex items-center gap-2"><span class="material-symbols-outlined text-primary">route</span> أحدث جلسات التصفح</h3><div class="overflow-x-auto"><table class="v8-session-table"><thead><tr><th>الوقت</th><th>المصدر</th><th>Referrer</th><th>الدخول</th><th>الخروج</th><th>صفحات</th><th>المدة</th><th>الجهاز</th><th>الحملة</th></tr></thead><tbody id="v8SessionsBody"></tbody></table></div></div>');}
  function analyticsParams(){const q=new URLSearchParams({limit:'500'});const from=document.getElementById('v8AnalyticsFrom')?.value||'',to=document.getElementById('v8AnalyticsTo')?.value||'';if(from)q.set('from',from);if(to)q.set('to',to);if(window.__v8SourceFilter)q.set('source',window.__v8SourceFilter);return q;}
  window.loadUniqueVisitors=async function(){try{injectAnalyticsSourceUI();const q=analyticsParams();const data=await api(`/api/analytics/visitors?${q}`);window.__v8Visitors=data.visitors||[];const stat=document.getElementById('stat-unique-visitors');if(stat)stat.textContent=data.uniqueCount||0;const sum=document.getElementById('v8SourceSummary');if(sum)sum.innerHTML=`<button onclick="window.v8FilterSource('')"><strong>كل المصادر</strong><span>${data.uniqueCount||0}</span></button>`+(data.sources||[]).map(x=>`<button onclick="window.v8FilterSource('${esc(x.source)}')"><strong>${esc(x.source)}</strong><span>${x.count}</span></button>`).join('');renderVisitorRows(window.__v8Visitors);const sess=await api(`/api/analytics/sessions?${q}`);window.__v8Sessions=sess.sessions||[];renderSessions(window.__v8Sessions);}catch(e){console.error(e);}};
  function renderVisitorRows(list){const tb=document.getElementById('analytics-visitors-table');if(!tb)return;tb.innerHTML=list.length?list.map(v=>`<tr><td>${v.knownCustomerName?`<b>${esc(v.knownCustomerName)}</b><small dir="ltr">${esc(v.knownCustomerPhone||'')}</small><small>طلبات: ${v.ordersCount||0}${v.lastOrderNumber?` • ${esc(v.lastOrderNumber)}`:''}</small>`:'<span class="v8-anon">زائر غير معروف</span>'}</td><td>${new Date(v.lastSeenAt||v.timestamp).toLocaleString('ar-EG')}</td><td><b class="v8-source-badge">${esc(v.source||'Direct')}</b><small>${esc(v.medium||'')}</small><small dir="ltr" title="${esc(v.referrer||'')}">${esc(v.referrer||'بدون Referrer')}</small></td><td>${esc(v.utmCampaign||'—')}<small>${esc(v.utmSource||'')}</small></td><td dir="ltr" title="${esc(v.lastLandingPage||'')}">${esc(v.lastLandingPage||'—')}</td><td>${esc(v.location||'غير معروف')}<small dir="ltr">${esc(v.ip||'')}</small></td><td>${esc(v.device||'غير معروف')}<small>${esc(v.browser||'')} • ${esc(v.os||'')} • ${esc(v.screen||'')} • ${esc(v.timezone||'')}</small></td><td>${esc(v.firstSource||'Direct')}<small dir="ltr">${esc(v.firstReferrer||'')}</small></td><td>${v.sessionCount||0}<small>${v.visitCount||0} page hits</small></td><td dir="ltr"><code>${esc(v.visitorId||'')}</code></td><td>${v.visitorId?`<button class="admin-action-btn v9-journey-btn" onclick="window.v9OpenVisitorJourney?.('${esc(v.visitorId)}')">رحلة الزائر</button>`:'—'}</td></tr>`).join(''):'<tr><td colspan="11">لا توجد بيانات</td></tr>';}
  function renderSessions(list){const tb=document.getElementById('v8SessionsBody');if(!tb)return;tb.innerHTML=list.map(s=>{const total=Number(s.activeSeconds||0)||Math.max(0,Math.round((new Date(s.lastSeenAt||s.startedAt)-new Date(s.startedAt))/1000));const min=Math.floor(total/60),sec=Math.floor(total%60);return `<tr><td>${new Date(s.startedAt).toLocaleString('ar-EG')}</td><td>${esc(s.source||'Direct')}<small>${esc(s.medium||'')}</small></td><td dir="ltr" title="${esc(s.referrer||'')}">${esc(s.referrer||'—')}</td><td dir="ltr">${esc(s.entryPage||'')}</td><td dir="ltr">${esc(s.exitPage||'')}</td><td>${s.pageCount||1}</td><td>${min?`${min}د ${sec}ث`:`${sec}ث`}</td><td>${esc(s.device||'')}<small>${esc(s.browser||'')} • ${esc(s.os||'')}</small></td><td>${esc(s.utmCampaign||'—')}</td></tr>`;}).join('');}
  window.v8FilterSource=async source=>{window.__v8SourceFilter=source||'';await window.loadUniqueVisitors?.();};

  function exportAnalyticsCsv(kind){
    const rows=kind==='sessions'?(window.__v8Sessions||[]): (window.__v8Visitors||[]);if(!rows.length){toast('لا توجد بيانات للتصدير');return;}
    const cols=kind==='sessions'?['startedAt','lastSeenAt','source','medium','referrer','utmSource','utmMedium','utmCampaign','entryPage','exitPage','pageCount','activeSeconds','ip','location','device','browser','os','visitorId']:['knownCustomerName','knownCustomerPhone','lastOrderNumber','ordersCount','lastSeenAt','source','medium','referrer','utmSource','utmMedium','utmCampaign','firstSource','firstReferrer','firstLandingPage','lastLandingPage','ip','location','country','city','device','deviceType','browser','os','screen','timezone','sessionCount','visitCount','visitorId'];
    const csv=[cols.join(',')].concat(rows.map(r=>cols.map(k=>`"${String(r[k]??'').replace(/"/g,'""')}"`).join(','))).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`technology-${kind}-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);
  }

  function refreshV8Permissions(){const b=document.getElementById('tab-growth');if(b)b.style.display=canManageGrowth()?'':'none';}

  function wrapSwitchTab(){if(!window.switchTab||window.switchTab.__v8)return;const old=window.switchTab;const wrapped=function(name){old(name);if(name==='growth')loadGrowth();if(name==='settings')loadCommerceSettings();if(name==='analytics')setTimeout(()=>window.loadUniqueVisitors?.(),100);};wrapped.__v8=true;window.switchTab=wrapped;}

  document.addEventListener('DOMContentLoaded',()=>{
    injectVariantBuilders();wrapEditModal();injectCommerceSettings();injectGrowthTab();injectAnalyticsSourceUI();wrapSwitchTab();refreshV8Permissions();
    setTimeout(()=>{wrapEditModal();refreshV8Permissions();if(canManage())loadCommerceSettings();},700);setTimeout(refreshV8Permissions,1800);setTimeout(refreshV8Permissions,3500);
  });
})();
