/* Technology Store V10.1 — Admin Readability + Workflow + Operations */
(() => {
  const esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const api=async(url,init={})=>{const r=await adminFetch(url,init);let d={};try{d=await r.json();}catch(_){}if(!r.ok)throw new Error(d.message||`HTTP ${r.status}`);return d;};
  const money=v=>`${Number(v||0).toLocaleString('ar-EG',{maximumFractionDigits:2})} ج.م`;
  const fmt=v=>v?new Date(v).toLocaleString('ar-EG'):'—';
  const has=p=>typeof hasPermission==='function'?hasPermission(p):true;

  function ensureCustomersPanel(){
    if(document.getElementById('tab-customers'))return;
    const nav=document.querySelector('.sidebar-nav'); if(!nav)return;
    const b=document.createElement('button');b.id='tab-customers';b.className='admin-tab w-full flex items-center gap-3 px-4 py-3 rounded-lg text-on-surface-variant font-bold text-sm transition-all hover:bg-surface-variant/50';b.onclick=()=>window.switchTab('customers');b.innerHTML='<span class="material-symbols-outlined text-[20px]">contacts</span><span>العملاء</span>';
    const orders=document.getElementById('tab-orders');(orders?.parentNode||nav).insertBefore(b,orders?.nextSibling||null);
    const parent=document.getElementById('panel-settings')?.parentElement;if(!parent)return;
    const panel=document.createElement('div');panel.id='panel-customers';panel.className='tab-panel hidden';panel.innerHTML=`
      <div class="v101-page-head"><div><small>المبيعات والعملاء</small><h2>ملفات العملاء</h2><p>عرض موحد لطلبات العميل، إجمالي مشترياته وآخر تعاملاته بدون إنشاء بيانات مكررة.</p></div><button class="v101-primary" onclick="window.v101LoadCustomers(1)"><span class="material-symbols-outlined">refresh</span> تحديث</button></div>
      <section class="glass-panel v101-toolbar"><div class="v101-search"><span class="material-symbols-outlined">search</span><input id="v101CustomerSearch" placeholder="ابحث بالاسم أو الهاتف أو رقم الطلب"></div><button onclick="window.v101LoadCustomers(1)">بحث</button><span id="v101CustomersCount">—</span></section>
      <section class="glass-panel v101-table-card"><div class="v101-table-scroll"><table class="v101-data-table"><thead><tr><th>العميل</th><th>رقم الهاتف</th><th>عدد الطلبات</th><th>إجمالي المشتريات</th><th>آخر طلب</th><th>آخر تعامل</th><th>التفاصيل</th></tr></thead><tbody id="v101CustomersBody"><tr><td colspan="7">جاري التحميل...</td></tr></tbody></table></div><div class="v101-pager"><button id="v101CustPrev">السابق</button><span id="v101CustPage">1 / 1</span><button id="v101CustNext">التالي</button></div></section>`;
    parent.appendChild(panel);document.getElementById('v101CustomerSearch').addEventListener('keydown',e=>{if(e.key==='Enter')window.v101LoadCustomers(1);});
  }
  let custPage=1,custPages=1;
  window.v101LoadCustomers=async(page=1)=>{if(!has('manage_orders'))return;const body=document.getElementById('v101CustomersBody');if(!body)return;body.innerHTML='<tr><td colspan="7">جاري التحميل...</td></tr>';try{const q=new URLSearchParams({page:String(Math.max(1,page)),limit:'25'}),search=document.getElementById('v101CustomerSearch')?.value.trim()||'';if(search)q.set('search',search);const d=await api(`/api/admin/customers?${q}`);custPage=d.page||1;custPages=d.pages||1;document.getElementById('v101CustomersCount').textContent=`${d.total||0} عميل`;document.getElementById('v101CustPage').textContent=`${custPage} / ${custPages}`;document.getElementById('v101CustPrev').disabled=custPage<=1;document.getElementById('v101CustNext').disabled=custPage>=custPages;document.getElementById('v101CustPrev').onclick=()=>window.v101LoadCustomers(custPage-1);document.getElementById('v101CustNext').onclick=()=>window.v101LoadCustomers(custPage+1);body.innerHTML=(d.customers||[]).length?d.customers.map(c=>`<tr><td><strong>${esc(c.name||'عميل')}</strong></td><td dir="ltr">${esc(c.phone||'')}</td><td><span class="v101-number-badge">${c.orders||0}</span></td><td><strong class="v101-money">${money(c.revenue)}</strong></td><td dir="ltr">${esc(c.lastOrderNumber||'—')}</td><td>${fmt(c.lastOrderAt)}</td><td><button class="v101-row-btn" onclick="window.v101OpenCustomer('${esc(c.phone)}')">فتح الملف</button></td></tr>`).join(''):'<tr><td colspan="7">لا توجد نتائج.</td></tr>';}catch(e){body.innerHTML=`<tr><td colspan="7" class="v101-error">${esc(e.message)}</td></tr>`;}};
  window.v101OpenCustomer=async phone=>{try{const d=await api(`/api/admin/customers/${encodeURIComponent(phone)}`);document.getElementById('v101CustomerModal')?.remove();const m=document.createElement('div');m.id='v101CustomerModal';m.className='v101-modal';m.innerHTML=`<div class="v101-modal-backdrop"></div><section class="v101-modal-card"><header><div><small>ملف العميل</small><h2>${esc(d.name||'عميل')}</h2><p dir="ltr">${esc(d.phone||'')}</p></div><button class="v101-modal-close">×</button></header><div class="v101-customer-kpis"><div><small>الطلبات</small><b>${d.orders?.length||0}</b></div><div><small>إجمالي المشتريات</small><b>${money(d.revenue)}</b></div><div><small>الاستبدال والاسترجاع</small><b>${d.returns?.length||0}</b></div></div><h3>الطلبات الأخيرة</h3><div class="v101-order-list">${(d.orders||[]).map(o=>`<button onclick="document.getElementById('v101CustomerModal')?.remove();switchTab('orders');setTimeout(()=>{const q=document.getElementById('ordersSearchInput');if(q){q.value='${esc(o.orderNumber)}';loadOrders(1)}},80)"><span><b dir="ltr">${esc(o.orderNumber)}</b><small>${fmt(o.createdAt)}</small></span><strong>${money(o.total)}</strong></button>`).join('')}</div></section>`;document.body.appendChild(m);const close=()=>m.remove();m.querySelector('.v101-modal-backdrop').onclick=close;m.querySelector('.v101-modal-close').onclick=close;}catch(e){alert(e.message);}};

  function injectNotificationCenter(){
    if(document.getElementById('v101Notifications'))return;const header=document.querySelector('#adminContainer header .flex.items-center.gap-2.md\\:gap-3')||document.querySelector('#adminContainer header > div:last-child');if(!header)return;
    const wrap=document.createElement('div');wrap.id='v101Notifications';wrap.className='v101-notifications';wrap.innerHTML=`<button id="v101NotifBtn" class="v101-notif-btn" aria-label="تنبيهات الإدارة"><span class="material-symbols-outlined">notifications</span><b id="v101NotifCount" class="hidden">0</b></button><div id="v101NotifMenu" class="v101-notif-menu hidden"><header><strong>التنبيهات</strong><button id="v101NotifRefresh"><span class="material-symbols-outlined">refresh</span></button></header><div id="v101NotifList"><p>جاري التحميل...</p></div></div>`;header.prepend(wrap);
    const btn=wrap.querySelector('#v101NotifBtn'),menu=wrap.querySelector('#v101NotifMenu');btn.onclick=e=>{e.stopPropagation();menu.classList.toggle('hidden');if(!menu.classList.contains('hidden'))loadNotifications();};wrap.querySelector('#v101NotifRefresh').onclick=loadNotifications;document.addEventListener('click',e=>{if(!wrap.contains(e.target))menu.classList.add('hidden');});setTimeout(loadNotifications,700);setInterval(()=>{if(!document.hidden)loadNotifications(true);},60000);
  }
  async function loadNotifications(silent=false){try{const d=await api('/api/admin/notifications'),count=document.getElementById('v101NotifCount'),list=document.getElementById('v101NotifList');if(count){count.textContent=d.count||0;count.classList.toggle('hidden',!d.count);}if(list)list.innerHTML=(d.items||[]).length?d.items.map(x=>`<button data-tab="${esc(x.tab)}" data-filter="${esc(x.filter||'')}"><span class="material-symbols-outlined">${esc(x.icon||'notifications')}</span><div><strong>${esc(x.title)}</strong><small>${esc(x.text||'')}</small></div></button>`).join(''):'<div class="v101-notif-empty"><span class="material-symbols-outlined">task_alt</span><p>لا توجد تنبيهات تحتاج إجراء.</p></div>';list?.querySelectorAll('button[data-tab]').forEach(b=>b.onclick=()=>{switchTab(b.dataset.tab);document.getElementById('v101NotifMenu')?.classList.add('hidden');if(b.dataset.filter)setTimeout(()=>window.setAdminStockFilter?.(b.dataset.filter),100);});}catch(e){if(!silent){const list=document.getElementById('v101NotifList');if(list)list.innerHTML='<p>تعذر تحميل التنبيهات.</p>';}}}

  function enhanceShippingManagement(){
    if(typeof window.openOrderDetails!=='function'||window.openOrderDetails.__v101)return;const old=window.openOrderDetails;const fn=function(id){old(id);setTimeout(()=>{const order=(window.adminOrdersCache||[]).find(o=>o._id===id),box=document.getElementById('orderDetailsContent');if(!order||!box||box.querySelector('.v101-shipping-admin'))return;const card=document.createElement('div');card.className='v101-shipping-admin';card.innerHTML=`<div><span class="material-symbols-outlined">local_shipping</span><div><small>بيانات الشحن</small><strong>${esc(order.shippingCarrier||'لم تحدد شركة الشحن')}</strong><p>${order.trackingNumber?`رقم التتبع: <b dir="ltr">${esc(order.trackingNumber)}</b>`:'لا يوجد رقم تتبع مسجل'}</p></div></div><button>تعديل بيانات الشحن</button>`;card.querySelector('button').onclick=()=>openShippingEditor(order);box.prepend(card);},60);};fn.__v101=true;window.openOrderDetails=fn;
  }
  function openShippingEditor(order){document.getElementById('v101ShippingModal')?.remove();const m=document.createElement('div');m.id='v101ShippingModal';m.className='v101-modal';m.innerHTML=`<div class="v101-modal-backdrop"></div><section class="v101-modal-card v101-shipping-editor"><header><div><small>الطلب ${esc(order.orderNumber)}</small><h2>بيانات شركة الشحن</h2><p>سيشاهد العميل هذه البيانات عند تتبع الطلب.</p></div><button class="v101-modal-close">×</button></header><div class="v101-form-grid"><label><span>شركة الشحن</span><input id="v101Carrier" value="${esc(order.shippingCarrier||'')}" placeholder="مثال: Bosta / Mylerz"></label><label><span>رقم البوليصة / التتبع</span><input id="v101TrackingNo" dir="ltr" value="${esc(order.trackingNumber||'')}"></label><label class="wide"><span>رابط التتبع الخارجي (اختياري)</span><input id="v101TrackingUrl" dir="ltr" value="${esc(order.trackingUrl||'')}" placeholder="https://..."></label><label><span>موعد التسليم المتوقع</span><input id="v101Eta" type="date" value="${order.estimatedDeliveryAt?new Date(order.estimatedDeliveryAt).toISOString().slice(0,10):''}"></label></div><footer><button class="secondary v101-modal-close2">إلغاء</button><button class="primary" id="v101SaveShipping">حفظ بيانات الشحن</button></footer></section>`;document.body.appendChild(m);const close=()=>m.remove();m.querySelector('.v101-modal-backdrop').onclick=close;m.querySelector('.v101-modal-close').onclick=close;m.querySelector('.v101-modal-close2').onclick=close;m.querySelector('#v101SaveShipping').onclick=async()=>{const btn=m.querySelector('#v101SaveShipping');btn.disabled=true;try{const d=await api(`/api/admin/orders/${order._id}/shipping`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({shippingCarrier:m.querySelector('#v101Carrier').value,trackingNumber:m.querySelector('#v101TrackingNo').value,trackingUrl:m.querySelector('#v101TrackingUrl').value,estimatedDeliveryAt:m.querySelector('#v101Eta').value||null})});Object.assign(order,d.order||{});showToast('✅ تم حفظ بيانات الشحن');close();window.openOrderDetails(order._id);}catch(e){alert(e.message);}finally{btn.disabled=false;}};}

  const selectedProducts=new Set();
  function injectBulkToolbar(){const table=document.getElementById('adminProductsTable');if(!table||document.getElementById('v101BulkToolbar'))return;const container=table.closest('.glass-panel')||table.parentElement;const bar=document.createElement('div');bar.id='v101BulkToolbar';bar.className='v101-bulk-toolbar';bar.innerHTML=`<div><span class="material-symbols-outlined">select_check_box</span><strong><b id="v101SelectedCount">0</b> محدد</strong></div><select id="v101BulkAction"><option value="">اختر إجراءً جماعياً</option><option value="hide">إخفاء المنتجات</option><option value="show">إظهار المنتجات</option><option value="featured">تمييز المنتجات</option><option value="unfeatured">إلغاء التمييز</option><option value="category">نقل إلى قسم</option><option value="price_percent">تعديل السعر بنسبة %</option></select><input id="v101BulkValue" class="hidden" placeholder="القيمة"><button id="v101BulkApply">تنفيذ</button><button id="v101BulkClear" class="secondary">إلغاء التحديد</button>`;container.insertBefore(bar,container.firstChild);bar.querySelector('#v101BulkAction').onchange=e=>{const inp=bar.querySelector('#v101BulkValue');inp.classList.toggle('hidden',!['category','price_percent'].includes(e.target.value));inp.placeholder=e.target.value==='category'?'اسم القسم':'النسبة مثال 10 أو -5';};bar.querySelector('#v101BulkClear').onclick=()=>{selectedProducts.clear();syncBulkSelection();decorateProductRows();};bar.querySelector('#v101BulkApply').onclick=applyBulkAction;
    new MutationObserver(()=>decorateProductRows()).observe(table,{childList:true});decorateProductRows();
  }
  function decorateProductRows(){const table=document.getElementById('adminProductsTable');if(!table)return;const products=window.filteredProducts||[],start=((window.currentPage||1)-1)*(window.ITEMS_PER_PAGE||20);[...table.querySelectorAll('tr.product-admin-row')].forEach((row,i)=>{const p=products[start+i];if(!p)return;row.dataset.productId=p._id;let cb=row.querySelector('.v101-product-check');if(!cb){cb=document.createElement('input');cb.type='checkbox';cb.className='v101-product-check';const cell=row.querySelector('.product-admin-cell');cell?.prepend(cb);cb.onclick=e=>e.stopPropagation();cb.onchange=()=>{cb.checked?selectedProducts.add(p._id):selectedProducts.delete(p._id);syncBulkSelection();};}cb.checked=selectedProducts.has(p._id);});syncBulkSelection();}
  function syncBulkSelection(){const e=document.getElementById('v101SelectedCount');if(e)e.textContent=selectedProducts.size;}
  async function applyBulkAction(){const action=document.getElementById('v101BulkAction')?.value||'',value=document.getElementById('v101BulkValue')?.value||'';if(!action)return alert('اختر الإجراء أولاً');if(!selectedProducts.size)return alert('حدد منتجاً واحداً على الأقل');if(!confirm(`تنفيذ الإجراء على ${selectedProducts.size} منتج؟`))return;try{await api('/api/admin/products/bulk-action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:[...selectedProducts],action,value,category:action==='category'?value:undefined})});showToast('✅ تم تنفيذ التعديل الجماعي');selectedProducts.clear();await window.loadAdminProducts?.(true);}catch(e){alert(e.message);}}

  function improveAnalyticsReadability(){const panel=document.getElementById('panel-analytics');if(!panel)return;panel.classList.add('v101-readable-panel');const visitors=document.getElementById('analytics-visitors-table')?.closest('.glass-panel');visitors?.classList.add('v101-visitors-card');document.querySelectorAll('#panel-analytics table,#panel-orders table,#panel-returns table,#panel-logs table').forEach(t=>t.classList.add('v101-readable-table'));}

  function arabizeLegacyLabels(){const replaces=new Map([['V9 Growth Intelligence','تحليل نمو المبيعات'],['Sales Recovery','استعادة المبيعات'],['After Sales','خدمات ما بعد البيع'],['Production Center','مركز تشغيل النظام'],['POS Sync Center','مزامنة نظام نقاط البيع'],['Cloud Backup Center','مركز النسخ الاحتياطي السحابي'],['Health Check','فحص حالة النظام'],['Checkout','إتمام الطلب'],['Direct','مباشر'],['Referrer','المصدر السابق'],['Visitor ID','معرّف الزائر'],['CSV الزوار','تصدير الزوار'],['CSV الجلسات','تصدير الجلسات']]);const walker=document.createTreeWalker(document.getElementById('adminContainer')||document.body,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){let v=n.nodeValue;for(const [a,b] of replaces)if(v.includes(a))v=v.split(a).join(b);n.nodeValue=v;}}

  function injectProfitCard(){const grid=document.getElementById('dashOrdersToday')?.closest('.grid');if(!grid||document.getElementById('v101ProfitCard'))return;const c=document.createElement('div');c.id='v101ProfitCard';c.className='glass-panel p-4 rounded-xl border border-outline-variant/30 v10-clickable-kpi';c.innerHTML='<p class="text-xs text-on-surface-variant">مجمل ربح اليوم</p><p id="v101ProfitValue" class="text-2xl font-bold text-emerald-400 mt-2">—</p><small>يظهر عند توفر تكلفة المنتج من نظام نقاط البيع</small>';grid.appendChild(c);c.onclick=()=>switchTab('intelligence');}
  async function refreshProfit(){try{const d=await api('/api/admin/dashboard');const e=document.getElementById('v101ProfitValue');if(e)e.textContent=d.orders?.costDataAvailable?money(d.orders.todayGrossProfit):'غير متاح';}catch(_){} }

  function wrapSwitch(){if(typeof window.switchTab!=='function'||window.switchTab.__v101)return;const old=window.switchTab;const fn=function(name){old(name);if(name==='customers')setTimeout(()=>window.v101LoadCustomers(custPage),50);if(name==='analytics')setTimeout(improveAnalyticsReadability,80);if(name==='products')setTimeout(()=>{injectBulkToolbar();decorateProductRows();},100);setTimeout(arabizeLegacyLabels,100);};fn.__v101=true;window.switchTab=fn;}
  function wrapDashboard(){if(typeof window.loadDashboard!=='function'||window.loadDashboard.__v101)return;const old=window.loadDashboard;const fn=async function(){await old();injectProfitCard();refreshProfit();setTimeout(loadNotifications,100);};fn.__v101=true;window.loadDashboard=fn;}

  function boot(){ensureCustomersPanel();injectNotificationCenter();enhanceShippingManagement();injectBulkToolbar();improveAnalyticsReadability();arabizeLegacyLabels();injectProfitCard();wrapSwitch();wrapDashboard();setTimeout(()=>{enhanceShippingManagement();injectBulkToolbar();improveAnalyticsReadability();arabizeLegacyLabels();loadNotifications(true);refreshProfit();},900);}
  document.addEventListener('DOMContentLoaded',boot);
})();
